services:
  - type: web
    name: dscommerce-app
    runtime: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: APP_PROFILE
        value:

      # Banco de dados
      - key: SPRING_DATASOURCE_URL
        value:
      - key: SPRING_DATASOURCE_USERNAME
        value:
      - key: SPRING_DATASOURCE_PASSWORD
        value:

      # Segurança e OAuth
      - key: CLIENT_ID
        value:
      - key: CLIENT_SECRET
        value:
      - key: ACCESS_TOKEN_URI
        value:

      # JWT
      - key: JWT_SECRET
        value:
      - key: JWT_DURATION
        value:

      # CORS
      - key: CORS_ORIGINS
        value:


